name: shelf_eventsource
description: A shelf handler for Server-Side Events (SSE).
version: 0.1.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-shelf_eventsource

environment:
  sdk: ">=1.0.0 <2.0.0"

dependencies:
  eventsource: ">=0.1.0 <0.2.0"
  shelf: ">=0.6.5 <0.7.0"
  stream_channel: ">=1.5.0 <2.0.0"

dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  # for the examples:
  shelf_route: ">=0.13.0 <0.15.0"
